### ISSUE TITLE
About reposting videos and introduction

### ISSUE THREAD

**Issue by LBY123165** [Quidvio/Vanilla-Stoneblock#3]
Hi. I'm a player from China, I saw your Vanilla stoneblock datapack on mordinth, my friends and I found this packet interesting, I would like to ask if I can repost your introduction video posted on youtube to bilibili.com, a Chinese video website and Minecraft resource introduction site mcmod.cn

**Comment by klinbee** [comment]
Absolutely sounds fine with me, just as long as I have credit I never mind people reposting! You're not the first one who has done it either, I always appreciate people that ask ahead of time to make sure.

**Comment by LBY123165** [comment]
Thank you very much for your permission
